/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminInboxRouteImport } from './routes/_authenticated/admin.inbox'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAssignerExploreRouteImport } from './routes/_authenticated/assigner.explore'
import { Route as AuthenticatedAssignerRequestsRouteImport } from './routes/_authenticated/assigner.requests'
import { Route as AuthenticatedAssignerStudentsRouteImport } from './routes/_authenticated/assigner.students'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardCoursesRouteImport } from './routes/_authenticated/dashboard.courses'
import { Route as AuthenticatedDashboardExploreRouteImport } from './routes/_authenticated/dashboard.explore'
import { Route as AuthenticatedDashboardRequestsRouteImport } from './routes/_authenticated/dashboard.requests'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardSupportRouteImport } from './routes/_authenticated/dashboard.support'
import { Route as AuthenticatedDashboardWatchCourseIdRouteImport } from './routes/_authenticated/dashboard.watch.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/admin/categories',
    path: '/admin/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInboxRoute = AuthenticatedAdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignerExploreRoute =
  AuthenticatedAssignerExploreRouteImport.update({
    id: '/assigner/explore',
    path: '/assigner/explore',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignerRequestsRoute =
  AuthenticatedAssignerRequestsRouteImport.update({
    id: '/assigner/requests',
    path: '/assigner/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignerStudentsRoute =
  AuthenticatedAssignerStudentsRouteImport.update({
    id: '/assigner/students',
    path: '/assigner/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCoursesRoute =
  AuthenticatedDashboardCoursesRouteImport.update({
    id: '/dashboard/courses',
    path: '/dashboard/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardExploreRoute =
  AuthenticatedDashboardExploreRouteImport.update({
    id: '/dashboard/explore',
    path: '/dashboard/explore',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRequestsRoute =
  AuthenticatedDashboardRequestsRouteImport.update({
    id: '/dashboard/requests',
    path: '/dashboard/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSupportRoute =
  AuthenticatedDashboardSupportRouteImport.update({
    id: '/dashboard/support',
    path: '/dashboard/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardWatchCourseIdRoute =
  AuthenticatedDashboardWatchCourseIdRouteImport.update({
    id: '/dashboard/watch/$courseId',
    path: '/dashboard/watch/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/assigner/explore': typeof AuthenticatedAssignerExploreRoute
  '/assigner/requests': typeof AuthenticatedAssignerRequestsRoute
  '/assigner/students': typeof AuthenticatedAssignerStudentsRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesRoute
  '/dashboard/explore': typeof AuthenticatedDashboardExploreRoute
  '/dashboard/requests': typeof AuthenticatedDashboardRequestsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/watch/$courseId': typeof AuthenticatedDashboardWatchCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/assigner/explore': typeof AuthenticatedAssignerExploreRoute
  '/assigner/requests': typeof AuthenticatedAssignerRequestsRoute
  '/assigner/students': typeof AuthenticatedAssignerStudentsRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesRoute
  '/dashboard/explore': typeof AuthenticatedDashboardExploreRoute
  '/dashboard/requests': typeof AuthenticatedDashboardRequestsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/watch/$courseId': typeof AuthenticatedDashboardWatchCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/assigner/explore': typeof AuthenticatedAssignerExploreRoute
  '/_authenticated/assigner/requests': typeof AuthenticatedAssignerRequestsRoute
  '/_authenticated/assigner/students': typeof AuthenticatedAssignerStudentsRoute
  '/_authenticated/dashboard/courses': typeof AuthenticatedDashboardCoursesRoute
  '/_authenticated/dashboard/explore': typeof AuthenticatedDashboardExploreRoute
  '/_authenticated/dashboard/requests': typeof AuthenticatedDashboardRequestsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/watch/$courseId': typeof AuthenticatedDashboardWatchCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/inbox'
    | '/admin/staff'
    | '/admin/users'
    | '/assigner/explore'
    | '/assigner/requests'
    | '/assigner/students'
    | '/dashboard/courses'
    | '/dashboard/explore'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/'
    | '/dashboard/watch/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/inbox'
    | '/admin/staff'
    | '/admin/users'
    | '/assigner/explore'
    | '/assigner/requests'
    | '/assigner/students'
    | '/dashboard/courses'
    | '/dashboard/explore'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard'
    | '/dashboard/watch/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/inbox'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/users'
    | '/_authenticated/assigner/explore'
    | '/_authenticated/assigner/requests'
    | '/_authenticated/assigner/students'
    | '/_authenticated/dashboard/courses'
    | '/_authenticated/dashboard/explore'
    | '/_authenticated/dashboard/requests'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/support'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/watch/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/inbox': {
      id: '/_authenticated/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AuthenticatedAdminInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assigner/explore': {
      id: '/_authenticated/assigner/explore'
      path: '/assigner/explore'
      fullPath: '/assigner/explore'
      preLoaderRoute: typeof AuthenticatedAssignerExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assigner/requests': {
      id: '/_authenticated/assigner/requests'
      path: '/assigner/requests'
      fullPath: '/assigner/requests'
      preLoaderRoute: typeof AuthenticatedAssignerRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assigner/students': {
      id: '/_authenticated/assigner/students'
      path: '/assigner/students'
      fullPath: '/assigner/students'
      preLoaderRoute: typeof AuthenticatedAssignerStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/courses': {
      id: '/_authenticated/dashboard/courses'
      path: '/dashboard/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/explore': {
      id: '/_authenticated/dashboard/explore'
      path: '/dashboard/explore'
      fullPath: '/dashboard/explore'
      preLoaderRoute: typeof AuthenticatedDashboardExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/requests': {
      id: '/_authenticated/dashboard/requests'
      path: '/dashboard/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof AuthenticatedDashboardRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/support': {
      id: '/_authenticated/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof AuthenticatedDashboardSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/watch/$courseId': {
      id: '/_authenticated/dashboard/watch/$courseId'
      path: '/dashboard/watch/$courseId'
      fullPath: '/dashboard/watch/$courseId'
      preLoaderRoute: typeof AuthenticatedDashboardWatchCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminInboxRoute: typeof AuthenticatedAdminInboxRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAssignerExploreRoute: typeof AuthenticatedAssignerExploreRoute
  AuthenticatedAssignerRequestsRoute: typeof AuthenticatedAssignerRequestsRoute
  AuthenticatedAssignerStudentsRoute: typeof AuthenticatedAssignerStudentsRoute
  AuthenticatedDashboardCoursesRoute: typeof AuthenticatedDashboardCoursesRoute
  AuthenticatedDashboardExploreRoute: typeof AuthenticatedDashboardExploreRoute
  AuthenticatedDashboardRequestsRoute: typeof AuthenticatedDashboardRequestsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSupportRoute: typeof AuthenticatedDashboardSupportRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardWatchCourseIdRoute: typeof AuthenticatedDashboardWatchCourseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminInboxRoute: AuthenticatedAdminInboxRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAssignerExploreRoute: AuthenticatedAssignerExploreRoute,
  AuthenticatedAssignerRequestsRoute: AuthenticatedAssignerRequestsRoute,
  AuthenticatedAssignerStudentsRoute: AuthenticatedAssignerStudentsRoute,
  AuthenticatedDashboardCoursesRoute: AuthenticatedDashboardCoursesRoute,
  AuthenticatedDashboardExploreRoute: AuthenticatedDashboardExploreRoute,
  AuthenticatedDashboardRequestsRoute: AuthenticatedDashboardRequestsRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardSupportRoute: AuthenticatedDashboardSupportRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardWatchCourseIdRoute:
    AuthenticatedDashboardWatchCourseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
